/**
 * @file emailService.ts
 * @description Service for sending email reports with PDF attachments
 */

import nodemailer from 'nodemailer';
import { ReportData } from './pdfService';

export interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  attachments?: Array<{
    filename: string;
    content: Buffer;
    contentType: string;
  }>;
}

export const sendEmail = async (options: EmailOptions): Promise<void> => {
  try {
    console.log('Email service: Starting email send...', {
      to: options.to,
      subject: options.subject,
      hasAttachments: !!options.attachments?.length,
      gmailUser: process.env.GOOGLE_EMAIL ? 'SET' : 'NOT SET',
      appPassword: process.env.GOOGLE_APP_PASSWORD ? 'SET' : 'NOT SET'
    });

    // Create transporter using App Password
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GOOGLE_EMAIL,
        pass: process.env.GOOGLE_APP_PASSWORD,
      },
    });

    console.log('Email service: Transporter created successfully');

    // Send email
    await transporter.sendMail({
      from: process.env.GOOGLE_EMAIL,
      to: options.to,
      subject: options.subject,
      html: options.html,
      attachments: options.attachments,
    });

    console.log('Email service: Email sent successfully');
  } catch (error) {
    console.error('Email service error:', {
      message: error instanceof Error ? error.message : 'Unknown error',
      stack: error instanceof Error ? error.stack : undefined
    });
    throw new Error(`Failed to send email: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
};

export const generateEmailHTML = (reportData: ReportData, recipientEmail: string): string => {
  const { dog, summary } = reportData;
  
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Breathing Report - ${dog.name}</title>
      <style>
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          max-width: 600px;
          margin: 0 auto;
          padding: 20px;
        }
        .header {
          background: #4f46e5;
          color: white;
          padding: 20px;
          text-align: center;
          border-radius: 8px 8px 0 0;
        }
        .content {
          background: #f8f9fa;
          padding: 20px;
          border-radius: 0 0 8px 8px;
        }
        .summary-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 15px;
          margin: 20px 0;
        }
        .summary-item {
          background: white;
          padding: 15px;
          border-radius: 6px;
          text-align: center;
          border-left: 4px solid #4f46e5;
        }
        .summary-value {
          font-size: 24px;
          font-weight: bold;
          color: #4f46e5;
        }
        .summary-label {
          font-size: 14px;
          color: #666;
          margin-top: 5px;
        }
        .footer {
          margin-top: 20px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          text-align: center;
          color: #666;
          font-size: 14px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Breathing Report</h1>
        <p>${dog.name}'s breathing data report</p>
      </div>
      
      <div class="content">
        <h2>Hello!</h2>
        <p>Please find attached the breathing report for <strong>${dog.name}</strong>.</p>
        
        <h3>Report Summary:</h3>
        <div class="summary-grid">
          <div class="summary-item">
            <div class="summary-value">${summary.totalLogs}</div>
            <div class="summary-label">Total Logs</div>
          </div>
          <div class="summary-item">
            <div class="summary-value">${summary.averageBPM.toFixed(1)}</div>
            <div class="summary-label">Average BPM</div>
          </div>
          <div class="summary-item">
            <div class="summary-value">${summary.lowestBPM}</div>
            <div class="summary-label">Lowest BPM</div>
          </div>
          <div class="summary-item">
            <div class="summary-value">${summary.highestBPM}</div>
            <div class="summary-label">Highest BPM</div>
          </div>
        </div>
        
        <p><strong>Date Range:</strong> ${summary.dateRange}</p>
        
        <p>The detailed report is attached as a PDF file.</p>
        
        <div class="footer">
          <p>This report was generated by PawPulse Breathing Monitor</p>
          <p>If you have any questions, please contact the pet owner.</p>
        </div>
      </div>
    </body>
    </html>
  `;
}; 